# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_fundconfig_fundfinance_fundscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundconfig',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundconfig',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fundconfig',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundfinance',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundfinance',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fundfinance',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundscale',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundscale',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fundscale',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
