# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_auto_20170214_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundNetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=200)),
                ('jjlx', models.CharField(max_length=100)),
                ('nav_a', models.FloatField()),
                ('nav_date', models.CharField(max_length=100)),
                ('nav_rate', models.FloatField()),
                ('per_nav', models.FloatField()),
                ('sg_states', models.CharField(max_length=100)),
                ('total_nav', models.FloatField()),
                ('yesterday_nav', models.FloatField()),
            ],
        ),
    ]
