# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_mutualfundrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('fundType', models.CharField(max_length=100)),
                ('nav', models.FloatField()),
                ('StarRating3', models.FloatField()),
                ('StarRating5', models.FloatField()),
                ('SD3Year', models.FloatField()),
                ('SD3YearComment', models.CharField(max_length=200)),
                ('DR3Year', models.FloatField()),
                ('DR3YearComment', models.CharField(max_length=200)),
                ('SR3Year', models.FloatField()),
                ('SR3YearComment', models.CharField(max_length=200)),
                ('ReturnYTD', models.FloatField()),
                ('updateDate', models.CharField(max_length=200)),
            ],
        ),
    ]
