# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_auto_20170221_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundBuyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('establishDate', models.CharField(max_length=200)),
                ('applyState', models.CharField(max_length=200)),
                ('returnState', models.CharField(max_length=200)),
                ('minBuy', models.FloatField()),
                ('frontCharge', models.FloatField()),
                ('backCharge', models.FloatField()),
                ('redeemFee', models.FloatField()),
                ('manageFee', models.FloatField()),
                ('trusteeFee', models.FloatField()),
                ('serviceFee', models.FloatField()),
                ('updateDate', models.CharField(max_length=200)),
            ],
        ),
    ]
