# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_mutualfundbuyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundReturnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('oneDayReturn', models.FloatField()),
                ('oneWeekReturn', models.FloatField()),
                ('oneMonthReturn', models.FloatField()),
                ('threeMonthReturn', models.FloatField()),
                ('sixMonthReturn', models.FloatField()),
                ('oneYearReturn', models.FloatField()),
                ('twoYearReturn', models.FloatField()),
                ('threeYearReturn', models.FloatField()),
                ('fiveYearReturn', models.FloatField()),
                ('tenYearReturn', models.FloatField()),
                ('totalReturn', models.FloatField()),
                ('threeYearStandard', models.FloatField()),
                ('threeYearRisk', models.FloatField()),
                ('updateDate', models.CharField(max_length=200)),
            ],
        ),
    ]
