# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0011_mutualfundmanagerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfundmanagerinfo',
            name='manageLength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mutualfundmanagerinfo',
            name='totalLength',
            field=models.IntegerField(),
        ),
    ]
