# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0012_auto_20170223_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundmanagerinfo',
            name='managerId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
