# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0016_remove_mutualfundmanagerdetail_managelength'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('threeYearSharp', models.FloatField()),
                ('threeYearStandard', models.FloatField()),
                ('threeYearRisk', models.FloatField()),
                ('StarRating3', models.FloatField()),
                ('StarRating5', models.FloatField()),
                ('updateDate', models.CharField(max_length=200)),
            ],
        ),
    ]
