# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0017_fundrecommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrecommend',
            name='fiveYearReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='oneMonthReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='oneWeekReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='oneYearReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='sixMonthReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='tenYearReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='threeMonthReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='threeYearReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='totalReturn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='twoYearReturn',
            field=models.FloatField(default=0),
        ),
    ]
