# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0018_auto_20170226_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrecommend',
            name='manageAchive',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='manageAvgAchive',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='manager',
            field=models.CharField(default='', max_length=200),
        ),
    ]
