# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0019_auto_20170226_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrecommend',
            name='establishDate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='manageStart',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='fundrecommend',
            name='resum',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
