# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0020_auto_20170227_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrecommend',
            name='totalStart',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
